#../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=6                     fg5cf1cb6f1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=6       --keepbuckets fg5cf1cb6t1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=7                     fg5cf1cb7f1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=7       --keepbuckets fg5cf1cb7t1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=5                     fg5cf1cb5f1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=5       --keepbuckets fg5cf1cb5t1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets="5:6;7"               fg5cf1cb567f1wk ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets="5;6;7" --keepbuckets fg5cf1cb567t1wk ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=1                     fg5cf1cb1f1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=1       --keepbuckets fg5cf1cb1t1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=2                     fg5cf1cb2f1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=2       --keepbuckets fg5cf1cb2t1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=3                     fg5cf1cb3f1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=3       --keepbuckets fg5cf1cb3t1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=4                     fg5cf1cb4f1wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=4       --keepbuckets fg5cf1cb4t1wk   ../ereps/ereps/dreps.mlb 7

 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=6                     fg5cf1cb6f2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=6       --keepbuckets fg5cf1cb6t2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=7                     fg5cf1cb7f2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=7       --keepbuckets fg5cf1cb7t2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=5                     fg5cf1cb5f2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=5       --keepbuckets fg5cf1cb5t2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets="5:6;7"               fg5cf1cb567f2wk ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets="5;6;7" --keepbuckets fg5cf1cb567t2wk ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=1                     fg5cf1cb1f2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=1       --keepbuckets fg5cf1cb1t2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=2                     fg5cf1cb2f2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=2       --keepbuckets fg5cf1cb2t2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=3                     fg5cf1cb3f2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=3       --keepbuckets fg5cf1cb3t2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=4                     fg5cf1cb4f2wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=4       --keepbuckets fg5cf1cb4t2wk   ../ereps/ereps/dreps.mlb 7

 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=6                     fg5cf1cb6f3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=6       --keepbuckets fg5cf1cb6t3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=7                     fg5cf1cb7f3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=7       --keepbuckets fg5cf1cb7t3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=5                     fg5cf1cb5f3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=5       --keepbuckets fg5cf1cb5t3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets="5:6;7"               fg5cf1cb567f3wk ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets="5;6;7" --keepbuckets fg5cf1cb567t3wk ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=1                     fg5cf1cb1f3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=1       --keepbuckets fg5cf1cb1t3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=2                     fg5cf1cb2f3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=2       --keepbuckets fg5cf1cb2t3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=3                     fg5cf1cb3f3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=3       --keepbuckets fg5cf1cb3t3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=4                     fg5cf1cb4f3wk   ../ereps/ereps/dreps.mlb 7
 ../../sf.opt ../ereps/dstarts.mlb ../ereps/drnums/nr-dreps.mlb -j 0.5 -J 0.1 --glocap --fofcap --buckets=4       --keepbuckets fg5cf1cb4t3wk   ../ereps/ereps/dreps.mlb 7

