REPS=freps
BASE1=$(REPS)-4
BASE2=$(REPS)-3
BASES=$(BASE1) $(BASE2)

QUE_PASA=srates
QUAD_PREFIX=$(QUE_PASA)-
#QUAD_SUFFIX=
DROP=rbucks-aranks-caps-
TABLE_PREFIX=$(QUAD_PREFIX)$(DROP)

SUMMARY_PREFIX=$(REPS)-$(QUE_PASA)
SUMMARY_PREFIX1=$(SUMMARY_PREFIX)-4
SUMMARY_PREFIX2=$(SUMMARY_PREFIX)-3
INPUT_PATH=$(REPS)/$(QUE_PASA)/tex
