# REPS
include ../reps.mk
WHATS_UP=overx
DIR_DROP=-self
QUE_PASA=$(WHATS_UP)$(DIR_DROP)
BASE=$(REPS)-$(QUE_PASA)

#QUAD_PREFIX=
#QUAD_SUFFIX=
#DROP=
#TABLE_PREFIX=overx-self

SUMMARY_PREFIX=$(BASE)
INPUT_PATH=$(REPS)/$(QUE_PASA)/tex
