# REPS
include ../reps.mk
include $(MK_DIR)/tex-defs.mk

QUE_PASA=$(WHATS_UP)$(DIR_DROP)

BASE1=$(REPS)-4
BASE2=$(REPS)-3
BASES=$(BASE1) $(BASE2)

SUMMARY_PREFIX=$(REPS)-$(QUE_PASA)
SUMMARY_PREFIX1=$(SUMMARY_PREFIX)-4
SUMMARY_PREFIX2=$(SUMMARY_PREFIX)-3
INPUT_PATH=$(REPS)/$(QUE_PASA)/tex

FROM_QUAD_SUFFIX=-suffix
QUAD_PREFIX=$(QUE_PASA)-
TABLE_PREFIX=$(QUAD_PREFIX)$(DROP)

TEXIT=$(TEX4RATES)
