# REPS
include ../reps.mk
BASE1=$(REPS)-4
BASE2=$(REPS)-3
BASES=$(BASE1) $(BASE2)

SUMMARY_PREFIX=$(REPS)-$(QUE_PASA)
SUMMARY_PREFIX1=$(SUMMARY_PREFIX)-4
SUMMARY_PREFIX2=$(SUMMARY_PREFIX)-3
INPUT_PATH=$(REPS)/$(QUE_PASA)/tex

QUAD_PREFIX=$(QUE_PASA)-
TABLE_PREFIX=$(QUAD_PREFIX)$(DROP)
