AVG=avg
MED=med

SELF=self
STAR=star
AUDS=auds

KIND_LIST=$(BASE_LIST:%=$(DREPS)-%)

LIST_AVG=$(KIND_LIST:%=$(AVG)-%)
LIST_MED=$(KIND_LIST:%=$(MED)-%)

LIST_AVG_SELF=$(LIST_AVG:%=$(SELF)-%)
LIST_AVG_STAR=$(LIST_AVG:%=$(STAR)-%)
LIST_AVG_AUDS=$(LIST_AVG:%=$(AUDS)-%)

LIST_MED_SELF=$(LIST_MED:%=$(SELF)-%)
LIST_MED_STAR=$(LIST_MED:%=$(STAR)-%)
LIST_MED_AUDS=$(LIST_MED:%=$(AUDS)-%)
