FROM_TABLE_PREFIX ?= prefix-
FROM_QUAD_PREFIX  ?= quad-prefix-
FROM_QUAD_SUFFIX  ?= -suffix

BASE1_LIST=$(shell cat $(LS_DIR)/$(BASE1).list)
BASE2_LIST=$(shell cat $(LS_DIR)/$(BASE2).list)

PRET1_LIST=$(if $(TABLE_PREFIX),$(BASE1_LIST:$(FROM_TABLE_PREFIX)%=$(TABLE_PREFIX)%),$(BASE1_LIST))
PRET2_LIST=$(if $(TABLE_PREFIX),$(BASE2_LIST:$(FROM_TABLE_PREFIX)%=$(TABLE_PREFIX)%),$(BASE2_LIST))

PRE1_LIST =$(if $(QUAD_PREFIX), $(PRET1_LIST:$(FROM_QUAD_PREFIX)%= $(QUAD_PREFIX)%), $(PRET1_LIST))
PRE2_LIST =$(if $(QUAD_PREFIX), $(PRET2_LIST:$(FROM_QUAD_PREFIX)%= $(QUAD_PREFIX)%), $(PRET2_LIST))

MLB1_LIST =$(filter %.mlb, $(PRE1_LIST))
MLB2_LIST =$(filter %.mlb, $(PRE2_LIST))

LINE1_LIST=$(if $(DROP),$(subst $(DROP),,$(MLB1_LIST)),$(MLB1_LIST))
LINE2_LIST=$(if $(DROP),$(subst $(DROP),,$(MLB2_LIST)),$(MLB2_LIST))
LINE_LIST =$(LINE1_LIST) $(LINE2_LIST)

LIST1     =$(PRE1_LIST:%$(FROM_QUAD_SUFFIX)=%$(QUAD_SUFFIX))
LIST2     =$(PRE2_LIST:%$(FROM_QUAD_SUFFIX)=%$(QUAD_SUFFIX))
LIST      =$(LIST1) $(LIST2) 
DIR_LIST  =$(filter-out %.mlb,$(LIST))